apiVersion: data.konghq.com/v1alpha1
kind: Plugin
metadata:
  name: cors-for-sample-service
spec:
  name: cors
  route:
    name: route-sample2
  config: |
    {
      "preflight_continue": false,
      "max_age": null,
      "methods": [
        "GET",
        "HEAD",
        "PUT",
        "PATCH",
        "POST",
        "DELETE",
        "OPTIONS",
        "TRACE",
        "CONNECT"
      ],
      "headers": null,
      "credentials": false,
      "exposed_headers": null,
      "origins": null
    }
